test

diff --git a/.github/workflows/build-and-run.yml b/.github/workflows/build-and-run.yml
--- a/.github/workflows/build-and-run.yml
+++ b/.github/workflows/build-and-run.yml
@@ -18,6 +18,7 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
+      
       - name: Echo workspace
         run: |
           echo 'test'
@@ -35,7 +36,7 @@ jobs:
           ./selfhostedrunner.exe
 
       # - name: Cleanup
-      #   if: always()
+      #   if: success() || failure()
       #   uses: actions/upload-artifact@v1
       #   with:
       #     name: test-results
