test

diff --git a/.github/workflows/build-and-run.yml b/.github/workflows/build-and-run.yml
--- a/.github/workflows/build-and-run.yml
+++ b/.github/workflows/build-and-run.yml
@@ -54,20 +54,21 @@ jobs:
           $response = Invoke-WebRequest -Uri $uri -Method POST -Body $body -UseBasicParsing -TimeoutSec $env:TIMEOUT
           $status_code = $response.StatusCode
           echo "info: $status_code"
-          echo "status_code=2" >> "$env:GITHUB_OUTPUT"
+          echo "status_code=$status_code" >> "$env:GITHUB_OUTPUT"
       
       - name: Get information on port
         id: pong
         run: |
-          echo "var: ${{ steps.ping.outputs.status_code }}"
           echo "Information Returned from Test: ${{ steps.ping.outputs.status_code }}"
 
-      - name: Set outputs
-        id: vars
-        run: echo "::set-output name=produc_tion::2"
-
-      - name: Check outputs
-        run: echo ${{ steps.vars.outputs.produc_tion }}
+      - name: Check status code
+        run: |
+          if (${{ steps.ping.outputs.status_code }} -ne 200) {
+            echo "HTTP request failed with status code ${{ steps.ping.outputs.status_code }}."
+            exit 1
+          } else {
+            echo "HTTP request successful with status code ${{ steps.ping.outputs.status_code }}."
+          }
 
       # - name: Cleanup
       #   if: success() || failure()
